In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])

In [2]:
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr1.shape

(5,)

## 

In [6]:
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

In [7]:
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [8]:
type(arr2)

numpy.ndarray

In [9]:
arr2.shape

(3, 5)

ndarray는 n-dimensional array라는 뜻!

In [11]:
arr3 = np.full(6, 7) # 7을 6번 채운 ndarray

In [12]:
arr3

array([7, 7, 7, 7, 7, 7])

In [13]:
arr4 = np.zeros(6, dtype=int)

In [14]:
arr4

array([0, 0, 0, 0, 0, 0])

In [15]:
arr5 = np.ones(6, dtype=int)

In [16]:
arr5

array([1, 1, 1, 1, 1, 1])

In [17]:
arr6 = np.random.random(6)

In [18]:
arr6

array([0.34776061, 0.37243969, 0.69247611, 0.78617383, 0.38293434,
       0.85674664])

In [19]:
arr7 = np.arange(6)

In [20]:
arr7

array([0, 1, 2, 3, 4, 5])

In [21]:
arr8 = np.arange(100, 120)

In [22]:
arr8

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [23]:
arr9 = np.arange(3, 16, 3)

In [24]:
arr9

array([ 3,  6,  9, 12, 15])

In [25]:
arr8[[1, 3, 5, 7, 9]]

array([101, 103, 105, 107, 109])

In [26]:
arr8[arr1]

array([101, 102, 103, 104, 105])

In [27]:
arr8[5:]

array([105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119])

In [28]:
arr8[5:10]

array([105, 106, 107, 108, 109])

In [29]:
arr8[:10]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [30]:
arr8[:10:2]

array([100, 102, 104, 106, 108])

In [31]:
arr8[::2]

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

In [32]:
arr1*2

array([ 2,  4,  6,  8, 10])

In [33]:
arr1+1

array([2, 3, 4, 5, 6])

In [35]:
arr1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [36]:
arr1-1

array([0, 1, 2, 3, 4])

In [37]:
arr1

array([1, 2, 3, 4, 5])

In [38]:
arr1+arr1

array([ 2,  4,  6,  8, 10])

In [39]:
arr1*arr1

array([ 1,  4,  9, 16, 25])

In [40]:
arr1/arr1

array([1., 1., 1., 1., 1.])

In [41]:
arr1-arr1

array([0, 0, 0, 0, 0])

In [42]:
arr1 > 4

array([False, False,  True,  True,  True])

In [43]:
arr1 % 2 == 0

array([False,  True, False,  True, False])

In [44]:
booleans = [True, True, False, True, True, False, True, True, False]

In [45]:
np.where(booleans)

(array([0, 1, 3, 4, 6, 7]),)

In [46]:
np.where(arr1 > 2)

(array([2, 3, 4]),)

In [47]:
filter = np.where(arr1 > 2)

In [48]:
arr1[filter]

array([3, 4, 5])

In [49]:
arr8.mean() #평균

109.5

In [51]:
np.median(arr8) #중앙값

109.5

In [52]:
arr8.std()

5.766281297335398

In [53]:
arr8.var()

33.25